name: flitch
description: A Flutter demo using the Twitch API.

dependencies:
  flutter:
    sdk: flutter
  twitch:
    path: ../../lab/twitch.dart
  flutter_webview_plugin: "^0.0.3"

flutter:
  uses-material-design: true
