name: flitch
description: A Flutter demo using the Twitch API.

dependencies:
  flutter:
    sdk: flutter
  twitch: ^0.3.2
  flutter_webview_plugin: "^0.0.3"

flutter:
  uses-material-design: true

  assets:
    - assets/placeholder.png