name: flitch
description: A Flutter demo using the Twitch API.

dependencies:
  flutter:
    sdk: flutter
  twitch:
    path: ../../lab/twitch.dart
  url_launcher: "^0.4.2+1"

flutter:
  uses-material-design: true
